# Makefile
#
# Created on: Jan 19, 2010
#     Author: Inspur OS Team
#
#

include ../Makefile.defs
include ../Makefile.prog

# Use DLSYM Instead!!
#LDFLAGS += -lfmd_eversholt -lfmd_topo
LDFLAGS += -L../../lib/libfmd -lfmd -lrt

PROG = fmd
