# Makefile.agent
#
# Created on: Jan 19, 2010
#     Author: Inspur OS Team
#
#

include ../../../Makefile.defs

LDFLAGS += -L../../../../lib/modules/libmod -L../../../../lib/modules/libagent -lfmd_module -lfmd_agent
LDFLAGS += -shared -fpic
CFLAGS += -I../../../../include

SRCS = $(wildcard *.c)
OBJS = $(SRCS:%.c=%.o)

%.o: %.c
	$(CC) $(CFLAGS) $(LDFLAGS) $<

all: $(OBJS)
	$(CC) -o $(PROGNAME) $(LDFLAGS) $<

clean:
	$(RM) $(OBJS) $(PROGNAME)

install:
	$(CP) $(CONFNAME) $(PLUGDIR)
	$(CP) $(PROGNAME) $(PLUGDIR)/$(PROGNAME).$(LIBVER)
#	$(LN) $(PLUGDIR)/$(PROGNAME).$(LIBVER) $(PLUGDIR)/$(PROGNAME)
	$(CP) $(PROGNAME) $(PLUGDIR)/$(PROGNAME)

uninstall:
	$(RM) $(PLUGDIR)/$(PROGNAME) $(PLUGDIR)/$(CONFNAME)
	$(RM) $(PLUGDIR)/$(PROGNAME).$(LIBVER)
