/*
 * fm_ata.h
 *
 * Copyright (C) 2009 Inspur, Inc.  All rights reserved.
 * Copyright (C) 2009-2010 Fault Managment System Development Team
 *
 * Created on: Apr 07, 2010
 *      Author: Inspur OS Team
 *  
 * Description:
 *      fm_ata.h
 *
 * The following ereports are generated by the userland disk-transport
 * module in response to errors reported by the disks.
 */

#ifndef	_FM_ATA_H
#define	_FM_ATA_H

#define	ATA_ERROR_CLASS		"io.ata"

#define	ATA_DISK_CLASS		"disk"

#define	FM_EREPORT_ATA_ERROR			"disk-error"
#define FM_EREPORT_PAYLOAD_ATA_HOURS		"timestamp"
#define FM_EREPORT_PAYLOAD_ATA_CAUSES		"causes"
#define FM_EREPORT_PAYLOAD_ATA_LBA		"address"

#define	FM_EREPORT_ATA_OVERTEMP			"over-temperature"
#define	FM_EREPORT_PAYLOAD_ATA_CURTEMP		"current-temperature"
#define	FM_EREPORT_PAYLOAD_ATA_THRESHTEMP	"threshold-temperature"

#define	FM_EREPORT_ATA_TESTFAIL			"self-test-failure"
#define	FM_EREPORT_PAYLOAD_ATA_RESULTCODE	"result-code"
#define	FM_EREPORT_PAYLOAD_ATA_ADDRESS		"address"
#define	FM_EREPORT_PAYLOAD_ATA_TIMESTAMP	"timestamp"
#define	FM_EREPORT_PAYLOAD_ATA_SEGMENT		"segment"

#define FM_EREPORT_ATA_SATAPHY                 	"sata-phy-event-counters"

#endif	/* _FM_ATA_H */
