# Makefile.prog
#
# Created on: Jan 19, 2010
#     Author: Inspur OS Team
#
#

SRCS = $(wildcard *.c)
OBJS = $(SRCS:%.c=%.o)
CFLAGS += -I../../include

%.o: %.c
	$(CC) $(CFLAGS) $<

all: $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $(PROG)

clean:
	$(RM) $(OBJS) $(PROG)

install:
	$(CP) $(PROG) $(FMDDIR)
	$(CP) $(PROG) $(CMDDIR)

uninstall:
	$(RM) $(FMDDIR)/$(PROG)
	$(RM) $(CMDDIR)/$(PROG)
