
#ifndef FMD_ERRNO_H_
#define FMD_ERRNO_H_ 1

#define FMD_SUCCESS		0
#define NODE_ID_INVALD 	-0x0001
#define OPENDIR_FAILED	-0x0002
#define OPENFILE_FAILED	-0x0003
#define READFILE_FAILED -0x0004

#endif /* FMD_ERRNO_H_ */
