# Makefile
#
# Created on: Oct 13, 2010
#     Author: Inspur OS Team
#
#

include ../Makefile.defs
include ../Makefile.prog

LDFLAGS += -L../../lib/libfmd_adm -L../../lib/libfmd_msg -lrt -lfmd_adm -lfmd_msg

PROG = fmadm
