#
#	Makefile for test cpumem event agent.
#            

CC      = gcc
CFLAGS  = -g -Wall -Wno-unused-function -DTEST_CMEA
COMPILE	= $(CC) $(CFLAGS) -c
LDFLAGS = -lpthread -lnl
          
KFM_LIB_DIR = ../../evtlib/kfm/kfmadm
INCLUDES = -I ../../../include/ \
           -I ../../include 	\
           -I $(KFM_LIB_DIR)
EVTLIB_DIR	= ../../evtlib
FMS_LIBFMD_DIR = ../../../lib/libfmd

PROGRAM = cmea_test

RM      = /bin/rm -f

LIBOBJS = cpumem_agent.o	\
		  evt_process.o		\
		  memdev.o			\
		  sysfs.o			\
		  tsc.o				\
		  cache.o			\
		  test.o			\
		  $(EVTLIB_DIR)/cpumem.o \
		  $(FMS_LIBFMD_DIR)/logging.o \
		  $(KFM_LIB_DIR)/kfm_nl.o \
		  $(KFM_LIB_DIR)/kfm_nl_policy.o \
		  $(KFM_LIB_DIR)/libkfm_cpumem.o 


all: $(PROGRAM)

$(PROGRAM): $(LIBOBJS)
	$(CC) -o $@ $(LIBOBJS) $(LDFLAGS)

%.o:%.c
	$(COMPILE) $(INCLUDES) -o $@ $^

clean:
	$(RM) $(LIBOBJS) $(PROGRAM)