# Makefile
#
# Create:	Jan, 17, 2011
# Author: Inspur OS Team
#

include ../Makefile.evtsrc

INCLUDES += -I/usr/include/libxml2
LDFLAGS	 += -lxml2

PROGNAME = evtsrc.proc.so
CONFNAME = evtsrc.proc.conf
